export const REQUESTING_DATA = 'REQUESTING_DATA';
export const RECEIVED_DATA = 'RECEIVED_DATA';
export const RECEIVED_UNIT_DATA = 'RECEIVED_UNIT_DATA';
export const REQUESTING_FAILED = 'REQUESTING_FAILED';
export const CHANGE_FILTER = 'CHANGE_FILTER';
